USE [master]
GO

/****** Object:  Database [certDB]    Script Date: 10/24/2014 4:59:17 PM ******/
CREATE DATABASE [certDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'certDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\certDB.mdf' , SIZE = 6144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'certDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\certDB_log.ldf' , SIZE = 4672KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [certDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [certDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [certDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [certDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [certDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [certDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [certDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [certDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [certDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [certDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [certDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [certDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [certDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [certDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [certDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [certDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [certDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [certDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [certDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [certDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [certDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [certDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [certDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [certDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [certDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [certDB] SET RECOVERY FULL 
GO

ALTER DATABASE [certDB] SET  MULTI_USER 
GO

ALTER DATABASE [certDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [certDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [certDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [certDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [certDB] SET  READ_WRITE 
GO

